### ISSUE TITLE
failed to connect to hinemos manager

### ISSUE THREAD

**Issue by tchoudha** [hinemos/hinemos#3]
Hello,

I am trying to use Rich client and trying to connect but I get the below error

Click [Details >>] button below to check the details.
  Manager1 : Unexpected Error.
  Failed to access the WSDL at: http://xx.xx.xx.xx:8080/HinemosWSAccessEndpointService?wsdl. It failed with: 
	http://xx.xx.xx.xx:8080/HinemosWSAccessEndpointService?wsdl.

**Comment by pango853** [comment]
Seems you forgot to put an slash(/) at the end of the Manager Connection URL.
 - wrong: http://xx.xx.xx.xx:8080/HinemosWS
 - correct: http://xx.xx.xx.xx:8080/HinemosWS/

**Comment by tchoudha** [comment]
Using http://xx.xx.xx.xx:8080/HinemosWS/ also doesn't work, is there any additional configuration involved

**Comment by pango853** [comment]
No, not any additional configuration required.

If it is not the link problem, then there must be something wrong at the manager side.
Please go to the manager host(xx.xx.xx.xx), and you can use the netstat command to troubleshoot.
`$ netstat -nat | fgrep 8080`

In addition, check the service status as well.
`$ systemctl status hinemos_manager.service`

If 8080 is not opened or anything goes wrong in the status result, probably you can find the causes from the manager log.

`$ cat /opt/hinemos/var/log/*.log`
Especially, 
`$ cat /opt/hinemos/var/log/hinemos_manager.log`

If you still cannot figure it out, please put some detail logs here.

**Comment by hinemos-geek** [comment]
Hi @tchoudha,
Hope my advices did help you figure out the problem. It will be very appreciated if you could let us know the result as well.
And, don't hesitate to let us know if you have any more issues.

**Comment by hinemos-geek** [comment]
Since we haven't heard any further reply on this for a while, we will treat this as **Resolved** and are now closing this issue. If there is anything else, please reopen it.
